spring:
  datasource:
    url: jdbc:h2:mem:vueloudea
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  graphql:
    graphiql:
      enabled: true
  h2.console.enabled: true